# -*- coding: utf-8 -*-
"""BankMarketing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OrsBJH1XrkJoSb-AKN1OiJ2Ss6NoIcNH
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

pip install ucimlrepo

from ucimlrepo import fetch_ucirepo
bank_marketing = fetch_ucirepo(id=222)

X = bank_marketing.data.features
Y = bank_marketing.data.targets

X.isna().sum() # Verificando valores nulos o basura

X = X.dropna(subset = ["job", "education"]) # Eliminando valores nulos
X.head()

# Eliminando columnas basura
X = X.drop("contact", axis=1)
X = X.drop("poutcome", axis=1)
X.head()

X.isna().sum() # Revisando la calidad de los datos de nuevo antes de continuar con el analisis

datos = X.join(Y)
datos

Y = datos[['y']]
Y

X = datos.drop("y", axis=1)
X

X = pd.get_dummies(X, columns=['job', 'marital'])
X

from sklearn.preprocessing import OrdinalEncoder
encoder = OrdinalEncoder()

X.loc[:,"default"] = encoder.fit_transform(X[["default"]])
X.loc[:,"housing"] = encoder.fit_transform(X[["housing"]])
X.loc[:,"loan"] = encoder.fit_transform(X[["loan"]])
X

map_dict = {"primary":1, "secondary":2, "tertiary":3}
X["education"] = X["education"].map(map_dict)
X

map_dict = {"jan":1, "feb":2, "mar":3, "apr":4, "may":5, "jun":6, "jul":7, "aug":8, "sep":9, "oct":10, "nov":11, "dec":12}
X["month"] = X["month"].map(map_dict)
X

from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)
X_train.shape, X_test.shape, Y_train.shape, Y_test.shape

from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()
model.fit(X_train, Y_train)
pd.DataFrame(model.get_params().items())

y_pred = model.predict(X_test)

from sklearn.metrics import confusion_matrix
from sklearn.metrics import ConfusionMatrixDisplay

cm = confusion_matrix(Y_test, y_pred)
cm

disp = ConfusionMatrixDisplay(confusion_matrix=cm)
disp.plot()
plt.show()

# precision de los datos
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(Y_test, y_pred)
accuracy

X.shape, Y.shape

datos = X.join(Y)
datos.shape

# Balanceo de datos

datos_true = datos[datos.y == "yes"]
datos_true.shape

datos_false = datos[datos.y == "no"]
datos_false.shape

datos_false = datos_false.sample(n = len(datos_true))
datos_false.shape

datos = pd.concat([datos_true, datos_false])
datos = datos.reset_index(drop=True)
datos.shape

datos.sample(n = 10)

y_new = datos[['y']]
X_new = datos.drop("y", axis=1)
X_new.shape, y_new.shape

X_train, X_test = train_test_split(X_new, test_size=0.2, random_state=42)
Y_train, Y_test = train_test_split(y_new, test_size=0.2, random_state=42)

X_train.shape, X_test.shape, Y_train.shape, Y_test.shape

model = DecisionTreeClassifier()
model.fit(X_train, Y_train)
y_pred = model.predict(X_test)

cm = confusion_matrix(Y_test, y_pred)
cm

from sklearn.model_selection import cross_val_score
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import GridSearchCV

y_new = np.ravel(y_new)

# lista de hyper params que se probaran (es la libreria que se encarga de combinarlos)
param_grid = [
    {'max_depth' : [2, 5, 10],
     'min_samples_leaf': [10, 25, 50],
     'criterion': ['gini', 'entropy']
    }]

# se configura el modelo a utilizar, junto con su lista de hyper params
model = GridSearchCV(DecisionTreeClassifier(), param_grid, n_jobs=-1)
model.fit(X_new, y_new)

# validacion cruzada
cv = StratifiedKFold(n_splits=5, shuffle=True)

# obtencion precisa y balanceada
accuracy = cross_val_score(model, X_new, y_new, cv=cv, scoring="balanced_accuracy")
print("Mejor modelo: {}".format(round(np.mean(accuracy), 3)))
print("Mejores parametros: {}".format(model.best_params_))

from sklearn.model_selection import cross_val_predict
y_pred = cross_val_predict(model, X_new, y_new, cv=cv)
cm = confusion_matrix(y_new, y_pred)
cm

disp = ConfusionMatrixDisplay(confusion_matrix=cm)
disp.plot()
plt.show()

accuracy = accuracy_score(y_new, y_pred)
accuracy

import pickle
filename = 'finalized_bank_marketing_model.sav'
pickle.dump(model, open(filename, 'wb'))