# -*- coding: utf-8 -*-
"""Example2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13Jcqo0eGG68gk1OAqfZt0Ow_ogc7hzFB

# Predicción de Precios de Casas con Machine Learning

## ¿Qué vamos a hacer?
Vamos a crear un modelo que pueda predecir el precio de una casa basándose en sus características como:
- Metros cuadrados
- Número de habitaciones
- Número de baños
- Antigüedad de la casa

## Pasos que vamos a seguir:
1. **Cargar los datos** - Leer nuestro archivo CSV con información de casas
2. **Explorar los datos** - Ver qué información tenemos
3. **Preparar los datos** - Organizar la información para el modelo
4. **Entrenar el modelo** - Enseñar al modelo a predecir precios
5. **Hacer predicciones** - Usar el modelo para predecir precios nuevos
6. **Evaluar resultados** - Ver qué tan bien funciona nuestro modelo
"""

# Importamos las librerías necesarias
import pandas as pd          # Para trabajar con datos (como Excel pero mejor)
import numpy as np           # Para hacer cálculos matemáticos
import matplotlib.pyplot as plt  # Para crear gráficos
import seaborn as sns        # Para crear gráficos más bonitos
from sklearn.model_selection import train_test_split  # Para dividir nuestros datos
from sklearn.linear_model import LinearRegression     # Nuestro modelo de machine learning
from sklearn.metrics import mean_squared_error, r2_score  # Para medir qué tan bien funciona

df = pd.read_csv('datos_casas.csv')

print("Informacion sobre nuestros datos")
print(f"Numero de casas: {len(df)}")
print(f"Numero de caracteristicas: {len(df.columns)}")
print("Primeras 5 casas:")
df.head()

print("Informacion estadistica basica:")
df.describe()

print("Hay datos faltantes o datos nulos?")
print(df.isnull().sum())

fig, axes = plt.subplots(2, 2, figsize=(15, 10))
fig.suptitle("Analisis de datos", fontsize=16, fontweight="bold")

axes[0, 0].scatter(df['metros_cuadrados'], df['precio'], alpha=0.6, color="blue")
axes[0, 0].set_xlabel("Metros cuadrados")
axes[0, 0].set_ylabel("Precio")
axes[0, 0].set_title("Metros cuadrados vs Precio")
axes[0, 0].grid(True, alpha=0.5)

axes[0, 1].scatter(df['habitaciones'], df['precio'], alpha=0.6, color="green")
axes[0, 1].set_xlabel("Numero de habitaciones")
axes[0, 1].set_ylabel("Precio")
axes[0, 1].set_title("Numero de habitacioes vs Precio")
axes[0, 1].grid(True, alpha=0.5)

axes[1, 0].scatter(df['banos'], df['precio'], alpha=0.6, color="red")
axes[1, 0].set_xlabel("Banos")
axes[1, 0].set_ylabel("Precio")
axes[1, 0].set_title("Banos vs Precio")
axes[1, 0].grid(True, alpha=0.5)

axes[1, 1].scatter(df['antiguedad'], df['precio'], alpha=0.6, color="navy")
axes[1, 1].set_xlabel("Antiguedad")
axes[1, 1].set_ylabel("Precio")
axes[1, 1].set_title("Antiguedad vs Precio")
axes[1, 1].grid(True, alpha=0.5)

plt.show()

X = df[['metros_cuadrados', 'habitaciones', 'banos', 'antiguedad']]
y = df['precio']

print("Caracteristicas que usaremos para predecir el precio:")
print(X.columns)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("Division de datos:")
print(f"Datos de entrenamiento: {X_train.shape[0]} casas")
print(f"Datos de prueba: {X_test.shape[0]} casas")

modelo = LinearRegression()
modelo.fit(X_train, y_train)

print("Coeficientes:")
for i, col in enumerate(X.columns):
  print(f"{col}: {modelo.coef_[i]}")

print("Interpretaciones:")
print("Un coeficiente positivo singifica que aumenta el precio")
print("Un coeficiente negativo singifica que disminuye el precio")
print("Un numero mas grande significa mayor impacto")

predicciones = modelo.predict(X_test)

print("Predicciones vs precios reales:")
print("="*50)

comparacion = pd.DataFrame({
    'Precio real': y_test,
    'Prediccion': predicciones,
    'Diferencias': y_test - predicciones
})

print(comparacion.head(9).round(2))

r2 = r2_score(y_test, predicciones)
mse = mean_squared_error(y_test, predicciones)
rmse = np.sqrt(mse)

print(f"R2: {r2}")
print(f"MSE: {mse}")
print(f"RMSE: {rmse}")

print("Que significan los numeros;")
if r2 > 0.8:
  print("El modelo es muy bueno")
elif r2 > 0.6:
  print("El modelo es bueno")
else:
  print("El modelo es malo")

fig, axes = plt.subplots(figsize=(15, 8))
fig.suptitle("Evaluacion del modelo", fontsize=16, fontweight="bold")

axes.scatter(y_test, predicciones , alpha=0.6, color="blue")
axes.plot([min(y_test), max(y_test)], [min(y_test), max(y_test)], color="red", linestyle="--", lw=2)
axes.set_xlabel("Precio real")
axes.set_ylabel("Prediccion")
axes.set_title("Prediccion vs Precio real")
axes.grid(True, alpha=0.5)

plt.show()

print("Predicciones de casas nuevas:")
print("="*50)

casas_nuevas = [
    [100, 3, 2, 5], # Casa 1
    [180, 4, 3, 2], # Casa 2
    [250, 5, 4, 1], # Casa 3
    [80, 2, 1, 10], # Casa 4
    [300, 6, 5, 0], # Casa 5
]

caracteristicas = ['metros_cuadrados', 'habitaciones', 'banos', 'antiguedad']

for i, casa in enumerate(casas_nuevas, 1):
  precio_predicho = modelo.predict([casa])[0]
  for j, caracteristica in enumerate(caracteristicas):
    print(f"{caracteristica}: {casa[j]}")
  print(f"Precio predicho: ${precio_predicho:,.2f}")
  print("-"*50)