# -*- coding: utf-8 -*-
"""Power-Consumption.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sPHauKcOl_uIRt30p2wjYUEWUtspusYX
"""

pip install ucimlrepo

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from ucimlrepo import fetch_ucirepo

individual_household_electric_power_consumption = fetch_ucirepo(id=235)
X = individual_household_electric_power_consumption.data.features
y = individual_household_electric_power_consumption.data.targets

X.shape

X.head()

X = X[["Date", "Time", "Global_active_power", "Voltage", "Global_intensity"]]
X.shape

X = X.rename(columns={"Global_active_power":'P', "Voltage":'V', "Global_intensity":'I'})
X.head()

X['P'] = pd.to_numeric(X['P'], errors="coerce")
X['V'] = pd.to_numeric(X['V'], errors="coerce")
X['I'] = pd.to_numeric(X['I'], errors="coerce")

X.isna().sum()

X = X.dropna()
X.shape

X.head()

X['P'].shift(periods = [2, 1, 0, -1]).head()

X['P'].shift(periods = [2, 1, 0, -1]).dropna().head()

X_P = X['P'].shift(periods = [2, 1, 0, -1]).dropna()
X_V = X['V'].shift(periods = [2, 1, 0]).dropna()
X_I = X['I'].shift(periods = [2, 1, 0]).dropna()

X_prepared = X_P.join(X_V).join(X_I)
X_prepared.head()

X_prepared.shape

y = X_prepared[["P_-1"]]
X = X_prepared.drop("P_-1", axis=1)
X.shape, y.shape

from sklearn.model_selection import train_test_split
X_train, X_test = train_test_split(X, test_size=100000, random_state=42)
X_train.shape, X_test.shape

2000000*0.2

y_train, y_test = train_test_split(y, test_size=100000, random_state=42)

y_train = np.reshape(y_train, -1)
y_test = np.reshape(y_test, -1)
y_train.shape, y_test.shape

from sklearn.neural_network import MLPRegressor
model = MLPRegressor(hidden_layer_sizes=(15, 5), max_iter=1500)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

rmse = np.sqrt(np.mean(np.square(y_test - y_pred)))

nrmse = (rmse / (y_train.max() - y_train.min())) * 100
print("Test NRMSE:", round(nrmse, 4), '%')

import pickle
filename = 'finalizes_model.sav'
pickle.dump(model, open(filename, 'wb'))