# -*- coding: utf-8 -*-
"""Clustering-Customers

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17KLQmpmbqOX4vi-bbJFfHQPHVSRZeaXs
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

pip install ucimlrepo

from ucimlrepo import fetch_ucirepo

wholesale_customers = fetch_ucirepo(id=292)

X = wholesale_customers.data.features
y = wholesale_customers.data.targets

datos = X.join(y)
datos.head()

datos.isna().sum()

from sklearn.cluster import KMeans

# lista de inercia que se usara para guardar   cada valor de K
inertia = []
cluster_max = 15 # probamos desde 2 hasta 15 clusters

for K in range(2, cluster_max+1):
  print("Ejecitando con K:", K)

  model = KMeans(n_clusters=K)
  model.fit(datos)

  inertia.append(model.inertia_)

fig = plt.figure(figsize=(8, 4))
plt.plot(range(2, cluster_max+1), inertia)
plt.xlabel("Cantidad de clusters (K)")
plt.ylabel("Inercia")
plt.grid(True, alpha=0.4)
plt.title("Metodo del codo - Eleccion del numero optimo de clusters")
plt.show()

model = KMeans(n_clusters=6)
model.fit(datos)

model.get_params()

datos['cluster'] = model.labels_

datos.head(n=10)

resumen = datos.groupby('cluster').mean().round(1)
resumen

resumen.plot.bar(figsize=(8, 4))
plt.title("Comparacion de caracteristicas por cluster")
plt.xlabel("Cluster")
plt.ylabel("Valor promedio")
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
plt.tight_layout()
plt.show()

# Normalizamos los datos para que todas las características estén en la misma escala (0-1)
#
# ¿Por qué normalizamos?
# - Las características tienen rangos muy diferentes
#   (ej: "Fresh" puede ir de 0 a 50,000, mientras que "Delicassen" de 0 a 5,000)
# - Sin normalización, las características con valores grandes dominarían el gráfico
# - Con normalización, podemos comparar todas las características en igualdad de condiciones
#
# Fórmula de normalización min-max:
#   valor_normalizado = (valor - mínimo) / (máximo - mínimo)
#   Resultado: valores entre 0 y 1
normalizado = (resumen - resumen.min()) / (resumen.max() - resumen.min())

import seaborn as sns

normalizado

# Heatmap del cluster
#
#¿Qué muestra el heatmap?
# - Filas: Cada cluster (0, 1, 2, 3, 4, 5)
# - Columnas: Cada característica (Fresh, Milk, Grocery, etc.)
# - Colores: Intensidad del valor (más oscuro = valor más alto)
#
# Ventajas del heatmap:
# - Fácil identificación de patrones visuales
# - Comparación rápida entre clusters
# - Identificación de características que destacan en cada grupo
#
# Interpretación:
# - Busca columnas con colores oscuros: características importantes de ese cluster
# - Compara filas: ver qué clusters son similares o diferentes
# - Esto te ayuda a entender el perfil de cada segmento de clientes
sns.heatmap(normalizado, annot=True, fmt='.2f', cmap='YlOrRd')
plt.title("Mapa de Calor - Perfil de cada Cluster (valores normalizados)")
plt.xlabel("Características")
plt.ylabel("Cluster")
plt.tight_layout()
plt.show()

# ============================================================================
# INTERPRETACIÓN DE RESULTADOS
# ============================================================================
# Ahora que tienes los clusters, puedes:
# 1. Nombrar cada cluster según su perfil (ej: "Restaurantes", "Supermercados")
# 2. Crear estrategias de marketing específicas para cada segmento
# 3. Identificar oportunidades de negocio en cada grupo
# 4. Personalizar ofertas según el perfil de compra de cada cluster