# -*- coding: utf-8 -*-
"""Example1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mMSqB8EmAt5g9QyOhkkdLjPQWAQs7tT-
"""

pip install ucimlrepo

pip install matplotlib

pip install pandas

from ucimlrepo import fetch_ucirepo
import pandas as pd
import matplotlib.pyplot as plt

# fetch dataset
infrared_thermography_temperature = fetch_ucirepo(id=925)

# data (as pandas dataframes)
X = infrared_thermography_temperature.data.features
y = infrared_thermography_temperature.data.targets

# metadata
print(infrared_thermography_temperature.metadata)

# variable information
print(infrared_thermography_temperature.variables)

print(X.head())

print(y.head())

print(X.columns.tolist())

print(y.columns.tolist())

print(X.describe())

print(y.describe())

if 'Age' in X.columns:
    plt.figure(figsize=(10, 6))
    plt.scatter(X['Age'], y[y.columns[0]], alpha = 0.5, c="navy", edgecolors="blue")
    plt.xlabel('Age', fontsize=12)
    plt.ylabel('Oral Temperature', fontsize=12)
    plt.title('Relation: Age vs Temperature', fontsize=14, fontweight='bold')
    plt.grid(True, alpha=0.3)
    plt.tight_layout()
    plt.show()

plt.figure(figsize=(10, 6))
plt.hist(y[y.columns[0]], bins=30, edgecolor='black', alpha=0.7, color="coral")
plt.xlabel('Oral Temperature', fontsize=12)
plt.ylabel('Frequency', fontsize=12)
plt.title('Temperature Distribution', fontsize=14, fontweight='bold')
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()